version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true
    [analyzers.meta]
    dialect = "typescript"
    
  [analyzers.meta]
  plugins = ["react"]